repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.18.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: flake8
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
      - id: isort
